# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiFiles/LoginPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 336)
        MainWindow.setMinimumSize(QtCore.QSize(400, 336))
        MainWindow.setStyleSheet("#LogPas{\n"
"    border-radius: 30px;\n"
"    background-color: white;\n"
"    border-color: rgb(0, 0, 0);\n"
"    border-width : 1.9px;\n"
"    border-style:solid;\n"
"}\n"
"#Test{\n"
"    background-color:#00000f;\n"
"    border-radius: 30px;\n"
"    border-color: green;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"}\n"
"QPushButton{\n"
"    background-color:transparent;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#3a0708;\n"
"}\n"
"QLineEdit{\n"
"    background-color:transparent;\n"
"    border: none;\n"
"    color:#717072;\n"
"    border-bottom: 1px solid #717072\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LogPas = QtWidgets.QFrame(self.centralwidget)
        self.LogPas.setMinimumSize(QtCore.QSize(300, 300))
        self.LogPas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LogPas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LogPas.setObjectName("LogPas")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.LogPas)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Test = QtWidgets.QFrame(self.LogPas)
        self.Test.setMinimumSize(QtCore.QSize(200, 200))
        self.Test.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Test.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Test.setObjectName("Test")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Test)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.Test)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Test)
        self.lineEdit_2.setAutoFillBackground(True)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.Test)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.Test)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.Test, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.LogPas, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Sign in"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
