# Form implementation generated from reading ui file 'Python/Downloader/videoandurl.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 70, 160, 128))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Status = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.Status.setInputMask("")
        self.Status.setObjectName("Status")
        self.verticalLayout.addWidget(self.Status)
        self.Urlline = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.Urlline.setObjectName("Urlline")
        self.verticalLayout.addWidget(self.Urlline)
        self.Choosethepath = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.Choosethepath.setObjectName("Choosethepath")
        self.verticalLayout.addWidget(self.Choosethepath)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Status.setPlaceholderText(_translate("Form", "Status..."))
        self.Urlline.setPlaceholderText(_translate("Form", "Enter the url.."))
        self.Choosethepath.setText(_translate("Form", "Choose the directory"))
        self.pushButton_2.setText(_translate("Form", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
